spring:
  application:
    name: demolition_king

  datasource:
    url: jdbc:mysql://54.180.226.214:3306/demolition_db?serverTimezone=Asia/Seoul
    username: root
    password: ssafy

  redis:
     host: 54.180.226.214
     port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
