#001  추후  Spring 배포시 변경 (로컬 Spring 기반 세팅)
spring:
  application:
    name: demolition_king

  datasource:
    #001
    #내부 배포용
#    url: jdbc:mysql://172.26.14.249/demolition?serverTimezone=Asia/Seoul
    #외부 local용
    url: jdbc:mysql://54.180.226.214/demolition?serverTimezone=Asia/Seoul
    username: root
    password: ssafy

  redis:
    #001
    #내부 배포용
#    host: 172.26.14.249
    #외부 local용
    host: 54.180.226.214
    port: 6379
    password: ssafyel06

  jpa:
    hibernate:
      ddl-auto: validate # update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com       # 실제 SMTP 호스트로 변경
    port: 587                  # SMTP 포트 (TLS)
    username: wlgns9807@gmail.com
    password: bdzlojbdirwaszca  # Gmail 의 경우 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
#    url: http://54.180.226.214:8080/v3/api-docs
#    로컬용
    url: http://localhost:8080/v3/api-docs
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    persist-authorization: true
    bearer-format: JWT
    default-model-expand-depth: 1
    default-model-rendering: example

swagger:
#  uri: http://54.180.226.214:8080
#  로컬용
  uri: http://localhost:8080

logging:
  level:
    root: DEBUG
    com.e106.demolition_king.game.service: DEBUG

jwt:
  secret: "nF4g7Jd9uKjH6Qz8YxM5Rg1TyP2Ls3VwHtGh4Jd6Kf9Lp0Mn"

#jwt:
#  secret: "nF4g7Jd9uKjH6Qz8YxM5Rg1TyP2Ls3VwHtGh4Jd6Kf9Lp0Mn"

#001
#  uri: http://54.180.226.214:8080
